name: Bug Report
description: Report a reproducible defect in ZeroClaw
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please provide a minimal reproducible case so maintainers can triage quickly.
        Do not include personal/sensitive data; redact and anonymize all logs/payloads.
        > **All fixes must be submitted as PRs referencing this issue** (e.g. `Fixes #123`). See [CONTRIBUTING.md](../blob/dev/CONTRIBUTING.md).
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the problem.
      placeholder: zeroclaw daemon exits immediately when ...
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Affected component
      options:
        - runtime/daemon
        - provider
        - channel
        - memory
        - security/sandbox
        - tooling/ci
        - docs
        - unknown
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - S0 - data loss / security risk
        - S1 - workflow blocked
        - S2 - degraded behavior
        - S3 - minor issue
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: What is happening now?
      placeholder: The process exits with ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen instead?
      placeholder: The daemon should stay alive and ...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide exact commands/config.
      placeholder: |
        1. zeroclaw onboard --interactive
        2. zeroclaw daemon
        3. Observe crash in logs
      render: bash
    validations:
      required: true
  - type: checkboxes
    id: pr_commitment
    attributes:
      label: Contribution Agreement
      options:
        - label: I understand that fixes must be submitted as a PR referencing this issue (e.g. `Fixes #<issue_number>`)
          required: true
